include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
